"""empty message

Revision ID: 191f496f07fe
Revises: 
Create Date: 2018-12-17 21:49:12.619535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '191f496f07fe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('emailid', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('uname', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('uname')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
