"""empty message

Revision ID: 7b5fa7d3e53b
Revises: 
Create Date: 2018-12-18 00:28:31.784830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b5fa7d3e53b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('emailid', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('uname', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('uname')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
